### ISSUE TITLE
Insecure download of hostapd

### ISSUE THREAD

**Issue by CyrilBrulebois** [U039b/PiRogue#1]
Hi,

Thanks for PiRogue, that looks fun!

Glancing at install.sh though, it seems fragile (version number can change if there's an updated in Debian stable) and insecure (no checks on the downloaded package) to fetch hostapd this way:

`wget http://ftp.fr.debian.org/debian/pool/main/w/wpa/hostapd_2.4-1+deb9u1_armhf.deb`

It would be better to leverage apt/gpg to avoid fetching and installing a rogue binary.

**Comment by U039b** [comment]
Now fixed in https://github.com/U039b/PiRogue-ansible/blob/master/roles/pirogue/tasks/main.yml#L78
