### ISSUE TITLE
Improve sysctl handling

### ISSUE THREAD

**Issue by CyrilBrulebois** [U039b/PiRogue#2]
Hi,

Dropping new lines into `/etc/sysctl.conf` might lead to a prompt when upgrading, since you're editing a configuration file. You might want to drop those lines under the `/etc/sysctl.d/` directory (e.g. in `/etc/sysctl.d/pirogue.conf`) to make it trivial to see what the default settings are, what PiRogue's installation script configured, and to make later upgrades smoother.

**Comment by U039b** [comment]
Now fixed in https://github.com/U039b/PiRogue-ansible/blob/master/roles/pirogue/tasks/main.yml#L118
