### ISSUE TITLE
Missing @reboot crontab entry

### ISSUE THREAD

**Issue by CyrilBrulebois** [U039b/PiRogue#3]
Hi,

It seems you were meaning to add an `@reboot` crontab entry but the `echo` ligne seems to only print it on screen?

**Comment by U039b** [comment]
Indeed, thank you :-)

**Comment by U039b** [comment]
It is now fixed in https://github.com/U039b/PiRogue/blob/master/install.sh#L80 But installation with Ansible has to be preferred now.
