### ISSUE TITLE
Document where to start from

### ISSUE THREAD

**Issue by CyrilBrulebois** [U039b/PiRogue#4]
Hi,

Current `README.md` mentions “PiRogue is based on a Raspberry Pi 3 and Kali GNU/Linux” but isn't exactly explicit as to where the starting point of an installation should be. Am I correct in assuming one should start from https://docs.kali.org/kali-on-arm/install-kali-linux-arm-raspberry-pi before running `install.sh`? It might be worth mentioning a Kali version as well, for which the installation process was developed/tested?

**Comment by U039b** [comment]
It is now fixed in the README https://github.com/U039b/PiRogue/blob/master/README.md :-)
